# Generated by Django 4.1.5 on 2023-01-13 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naxa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_district', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_municipality', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_province', models.CharField(max_length=155)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='District',
        ),
        migrations.AddField(
            model_name='location',
            name='district',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='naxa.district'),
        ),
        migrations.AlterField(
            model_name='location',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naxa.municipality'),
        ),
        migrations.AlterField(
            model_name='location',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naxa.province'),
        ),
    ]
