# Generated by Django 4.1.5 on 2023-01-13 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naxa', '0003_alter_district_name_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='agency_name',
        ),
        migrations.RemoveField(
            model_name='projectdetails',
            name='agency',
        ),
        migrations.AddField(
            model_name='agency',
            name='doner_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='agency',
            name='executing_agency',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='doner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naxa.agency'),
        ),
    ]
