# Generated by Django 4.1.5 on 2023-01-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naxa', '0004_remove_agency_agency_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
